---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCp4fh4vG93M2J7+06pHJnm8znRODVpRhyv4AFQwpdSEnP1xsChQD/e22yItebIMEGIejQuGUB3fv3y2JGpoBfZe6v2dDSIMRcCuzjJNo6KqA9XVl0CESv0lSirEMnIlUNCfiR9dqWl17ECZffkSKlVDT60w1FbYg91TshAFIcr1MxPQlsgsC2pPzVmQgtxALk1+LaXxVm7i7IhcwNyNdL51ocn6tc0h0h8ghyPYOx9lX6eT8IaddvzHgccKpuy3TXXwj9qhzvjpftHOkgQUkb32dmP/hgfnRxZKJQOZN1BgfRBlPUkEHIJ+hWAZpyOUZd3joCgzjP2sQh6s1Ifp6Q5NRjLI2lgb61zAY2SQe2voF6PEQeCPenP7zZEcDyzift1ZYqZmwxWc+dcKvFwuBoGl8OY/0C7okmH60uN7th2xJJQ+JaA3dZ55wJPhABeKyxRKszISsIqCFTEuLvtjzLucSYlZUqm9jY+zzfijbIy/FTNIgR1BeBODU4u3Rg6GJG4CkrQd1kaixYdEXfVwjxX9Sv0clFXnOjaTl4u+kApqh3Si+2MNv3MwlSChWPS88WHVAZH47jtfEVTBtVDMcmcGbelmje9ZB4txvsRaGUcIjM3fHpWw9JLBsjxlJMexiSWAH4XqahPRmRAmVuiEz/h/9vRDmfyFcHEa3OZQ7X/Oj5+YXAsJBQMgvZ35/GlYbQvUsiGAXfgqQiaqA==
    admin-user: AgBqQUT6jlx6ORN++yu/YVFincAVV472APmzC4CGobBunKQNVz9C3XP4gB/8ruMts9Uf1aDwn3fgaX3/zyArGWcLVQX216JVsIzNYTaEuHDx7Hj4tBn2TclsryGPKORKZICVvDVllU5gSM4+7VgE2hjecX9EU7fRsvJ2jyPi3epjwTVTgzyCBgcKmZtlrLAeqzAKQXglIXu+HDtu8257BtFiTksDL23sHtbFIAA4NRV/6f/m8LizhtCuiU9jBfBGsO980IG0lfQUcdHrksI6dIIj8uOGfDxOrDp3kVj6z6LCylUKVClfR96hl4X+aE+LVA64QWbh8tP/uICO4/LZKu+GswC/KUEJeu9dUvSt7p2t0O/aCzEJ7bMgh2dpQx1+IzXFj+c1dSO4dB2w+hX3t6RSeygqGfFO7XvfIoGa9ze9tSM7d4k6zJZ3N481FM4hFrcRaSI0qMcilkt94aRzEKKrl6s30trgypWCxYaXRfHAqcRMIKJOzTizvUyJiF6EfAATltZQZQXsAhS+9NN8k6rzfgzIbZyF17wlRC8aoAlGMcTFeZ+y2gyy2nPC2XnQOejTd6UfHyA/Btw7kGJmce6FVCLJrtKbKwSYCVbuRdF6a+vPemh6J2+unA8pnwHy5nuh07g/dKelunErBse1LbNfzV92WI5xo+pfMqSO0ga+RJ33yXtwpDTPlnIewNbCmFaO+OfwDQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
